// Words that must never appear in gameplay (synonyms or distractors).
// Matching is exact, case-insensitive — substring matches are NOT blocked.
export const BLOCKED_WORDS = new Set([
  // profanity
  'ass', 'asses', 'arse', 'arses', 'asshole', 'assholes', 'arsehole', 'arseholes',
  'fuck', 'fucker', 'fuckers', 'fucking', 'fucked', 'fucks', 'motherfucker',
  'shit', 'shits', 'shite', 'shitty', 'bullshit',
  'bitch', 'bitches', 'bitchy',
  'bastard', 'bastards',
  'cunt', 'cunts',
  'cock', 'cocks',
  'dick', 'dicks',
  'prick', 'pricks',
  'pussy', 'pussies',
  'whore', 'whores',
  'slut', 'sluts',
  'twat', 'twats',
  'wank', 'wanker', 'wankers', 'wanking',
  'bollocks',
  'bugger', 'buggers',
  'tit', 'tits', 'titty', 'titties',
  'boob', 'boobs',
  'damn', 'dammit', 'damned',
  'crap', 'crappy',
  'hell',
  'bloody',
  // sexual
  'penis', 'penises',
  'vagina', 'vaginas',
  'vulva', 'vulvas',
  'anus', 'anuses',
  'scrotum',
  'testicle', 'testicles',
  'erection', 'erections',
  'ejaculation',
  'sperm',
  'porn', 'porno', 'pornography', 'pornographic',
  'erotic', 'erotica',
  'horny',
  'orgasm', 'orgasms', 'orgasmic',
  'masturbate', 'masturbation',
  'rape', 'raping', 'raped', 'rapist', 'rapists',
  'molest', 'molestation',
  'nude', 'nudity', 'nudist', 'nudism',
  'naked',
  'sexy',
  // slurs
  'nigger', 'niggers', 'nigga',
  'faggot', 'faggots', 'fag', 'fags',
  'retard', 'retarded',
  'spastic',
  'dyke', 'dykes',
]);
